# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNtC40p-fhRjYvVM7lZIXIJTZO_7wzIG
"""

import numpy as np
import streamlit as st
import pickle

model = pickle.load(open('housingprediction.pkl','rb'))
st.title("Housing Price Prediction")

car = int(st.text_input("Enter Car Parking : ","2"))
land_size = float(st.text_input("Enter Land Size: ","10000"))
building_area = float(st.text_input("Enter Building area: ","10000"))
year_built = float(st.text_input("Enter Year Built: ","2000"))

featureInput = np.array([[car,land_size, building_area, year_built]])

sal = model.predict(featureInput)

st.write(f'Hello, *World!* :sunglasses: . Predicted Price is : {sal} ')



